#!/usr/bin/env bash

mkdir /etc/banhttpreqstrings
mkdir /var/lib/banhttpreqstrings

cp banhttpreqstrings.yaml /etc/banhttpreqstrings/

export DEBIAN_FRONTEND=noninteractive
apt install -y python3-systemd
apt install -y python3-watchdog

pip install . --break-system-packages
