[project]
name = 'banhttpreqstrings'
version = '1'

classifiers = [
    'Programming Language :: Python :: 3',
    'Operating System :: Linux'
]


[project.scripts]
banhttpreqstrings = 'banhttpreqstrings:main'
